
### 获取所有服务实例
GET http://localhost:8484/findAll?serviceName=cn.liz.lizrpc.UserService

### 获取所有服务实例
GET http://localhost:8485/findAll?serviceName=cn.liz.lizrpc.UserService

### 注册实例
POST http://localhost:8485/register?serviceName=cn.liz.lizrpc.UserService
Content-Type: application/json

{
  "context": "lizrpc",
  "host": "127.0.0.1",
  "port": 8083,
  "scheme": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "red"
  }
}

### 取消注册
POST http://localhost:8484/unregister?serviceName=cn.liz.lizrpc.UserService
Content-Type: application/json

{
  "context": "lizrpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http"
}

### 获取版本号
GET http://localhost:8484/version?service=cn.liz.lizrpc.UserService

### 获取当前节点
GET http://localhost:8484/info
###
GET http://localhost:8485/info
###
GET http://localhost:8486/info
###
GET http://localhost:8486/cluster

###
GET http://localhost:8485/setLeader

###
GET http://localhost:8484/snapshot




